apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-chart.fullname" . }}
data:
  SERVER_PORT: {{ .Values.port | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-chart.fullname" . }}
type: Opaque
data:
  postgres-username: {{ .Values.postgresql.username | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}