{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-chart.serviceAccountName" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "user-chart.fullname" . }}
rules:
  - apiGroups: ["batch","extensions"]
    resources: ["jobs"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "user-chart.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "user-chart.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "user-chart.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}