apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      name: web
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-chart.fullname" . }}-auth
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}-auth
spec:
  type: {{ .Values.authService.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.authService.port }}
      targetPort: {{ .Values.portAuth }}
      name: web-auth
  selector:
    {{- include "user-chart.selectorLabels" . | nindent 4 }}-auth
