# Default values for user-chart.
replicaCount: 2

image:
  repository: shaplovdv/userapp
  pullPolicy: Always
  tag: "0.5.0"

initImage:
  repository: ghcr.io/groundnuty/k8s-wait-for
  pullPolicy: Always
  tag: v1.6

jobImage:
  repository: shaplovdv/userjob
  pullPolicy: Always
  tag: "latest"

postgresql:
  enabled: true
  username: postgres
  auth:
    postgresPassword: mysecretpassword
  metrics:
    serviceMonitor:
      enabled: true
      interval: 5s
    enabled: true
  global:
    postgresql:
      auth:
        database: postgres

port: "8000"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "sa-migration"

service:
  type: NodePort
  port: 80

ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: arch.homework
      paths:
        - path: /(.*)
          pathType: Prefix

metrics:
  serviceMonitor:
    enabled: true