# Default values for user-chart.
replicaCount: 2

image:
  repository: shaplovdv/userprofile
  pullPolicy: IfNotPresent
  tag: "1.1"

imageAuth:
  repository: shaplovdv/userauth
  pullPolicy: IfNotPresent
  tag: "1.7"

initImage:
  repository: ghcr.io/groundnuty/k8s-wait-for
  pullPolicy: IfNotPresent
  tag: v1.6

jobImage:
  repository: shaplovdv/userjob
  pullPolicy: IfNotPresent
  tag: "3.3"

postgresql:
  enabled: true
  username: postgres
  auth:
    postgresPassword: mysecretpassword
  metrics:
    serviceMonitor:
      enabled: true
      interval: 5s
    enabled: true
  global:
    postgresql:
      auth:
        database: postgres

port: "8000"
portAuth: "8001"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "sa-migration"

service:
  type: NodePort
  port: 80
authService:
  type: NodePort
  port: 81

ingress:
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/internal.*" {
          deny all;
          return 403;
        }
  hosts:
    - host: arch.homework
      paths:
        - path: /(.*)
          pathType: Prefix
          serviceSuffix: ""
          svcPort: 80

ingressAuth:
  className: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /(register|login|logout)
          pathType: Prefix
          serviceSuffix: "-auth"
          svcPort: 81

metrics:
  serviceMonitor:
    enabled: true